
name: Run Add-On
on:
  workflow_dispatch:
  schedule:
    # Run at 1:22 AM every day
    - cron:  "22 1 * * *"

jobs:
  Run-Add-On:
    uses: Muckrock/documentcloud-addon-workflows/.github/workflows/run-addon.yml@main
    with:
      git-commit: true
